name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish Windows
      run: dotnet publish -o publish-win -r win-x64 -c release --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true nats-tools.csproj 
    - name: Publish Linux
      run: dotnet publish -o publish-linux -r linux-x64 -c release --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true nats-tools.csproj
      
    - name: Artifact Linux
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: publish-linux/*
    - name: Artifact Windows
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: publish-win/*
      
